server:
  port: 8081
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    addresses:amqps://yssodmxc:BhMFd6fqf-ikjqFmuOKU4zh8vuOdntCc@woodpecker.rmq.cloudamqp.com/yssodmxc
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/ms-user
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}